services:
  postgresql:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bootcamp
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: baixio-infra
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
      - ./src/docs:/app/src/docs
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
